#!/usr/bin/env python3
"""Generate workflow_chips_gp.csv for General Medicine / GP workflows."""

import csv

fields = ['workflow_id','specialty_id','chip_id','group','chip_text','order','search_terms','tags']
SPEC = 'General Medicine / GP'
rows = []
order_counter = {}  # wf_id -> int

def chip(wf_id, group, text, search='', tags=''):
    o = order_counter.get(wf_id, 0) + 1
    order_counter[wf_id] = o
    prefix = {'symptoms':'s', 'relevant_negatives':'n', 'exam_findings':'e',
              'red_flags':'r', 'investigations':'i', 'plan_phrases':'p', 'follow_up':'f'}
    ch_id = f'{wf_id}-{prefix[group]}{o}'
    rows.append([wf_id, SPEC, ch_id, group, text, o, search, tags])

# ====================================================================
# 1. gp-fever-urti: Fever / Viral URTI
# ====================================================================
WF = 'gp-fever-urti'
chip(WF,'symptoms','fever','fever, pyrexia, high temperature','acute')
chip(WF,'symptoms','cough','cough, dry cough','acute')
chip(WF,'symptoms','sore throat','sore throat, throat pain, pharyngitis','acute')
chip(WF,'symptoms','runny nose','runny nose, rhinorrhea, nasal discharge','acute')
chip(WF,'symptoms','nasal congestion','nasal congestion, blocked nose, stuffy nose','acute')
chip(WF,'symptoms','body aches','body aches, myalgia, muscle pain','acute')
chip(WF,'symptoms','chills','chills, rigors, feeling cold','acute')
chip(WF,'symptoms','headache','headache, head pain','acute')
chip(WF,'symptoms','fatigue','fatigue, tiredness, malaise','acute')
chip(WF,'symptoms','decreased appetite','decreased appetite, anorexia, not hungry','acute')
chip(WF,'symptoms','sneezing','sneezing, sneezing fits','acute')
chip(WF,'relevant_negatives','no shortness of breath','no SOB, no dyspnea, breathing fine','respiratory')
chip(WF,'relevant_negatives','no chest pain','no chest pain, no CP','cardiac')
chip(WF,'relevant_negatives','no neck stiffness','no neck stiffness, no meningism','neuro')
chip(WF,'relevant_negatives','no persistent vomiting','no vomiting, no emesis','gi')
chip(WF,'relevant_negatives','no confusion','no confusion, no altered mental state','neuro')
chip(WF,'relevant_negatives','no rash','no skin rash, no exanthem','dermatology')
chip(WF,'relevant_negatives','no ear pain','no ear pain, no otalgia','ent')
chip(WF,'relevant_negatives','no urinary symptoms','no dysuria, no urinary frequency','renal')
chip(WF,'exam_findings','afebrile','afebrile, no fever in clinic','vitals')
chip(WF,'exam_findings','febrile','febrile, temperature elevated','vitals')
chip(WF,'exam_findings','throat congested','throat congested, pharyngeal erythema','ent')
chip(WF,'exam_findings','tonsils normal','tonsils normal, no tonsillar enlargement','ent')
chip(WF,'exam_findings','tonsillar exudate','tonsillar exudate, white spots','ent')
chip(WF,'exam_findings','cervical lymphadenopathy','cervical LNs, neck lymph nodes','ent')
chip(WF,'exam_findings','chest clear on auscultation','chest clear, lung fields clear','respiratory')
chip(WF,'exam_findings','wheezes','wheezes, expiratory wheeze','respiratory')
chip(WF,'exam_findings','no respiratory distress','no respiratory distress, no RD','respiratory')
chip(WF,'exam_findings','hydration adequate','hydrated, mucus membranes moist','general')
chip(WF,'exam_findings','decreased skin turgor','decreased turgor, dry mucus membranes','general')
chip(WF,'red_flags','breathing difficulty','dyspnea, tachypnea, respiratory distress','respiratory,high_safety')
chip(WF,'red_flags','persistent high fever','high fever persistent >3 days','acute,high_safety')
chip(WF,'red_flags','confusion','confusion, drowsiness, lethargy','neuro,high_safety')
chip(WF,'red_flags','neck stiffness','neck stiffness, meningeal signs','neuro,high_safety')
chip(WF,'red_flags','dehydration','dehydration signs, reduced urine output','general,high_safety')
chip(WF,'red_flags','immunocompromised state','immunocompromised, on immunosuppressants','chronic,high_safety')
chip(WF,'red_flags','petechial rash','petechiae, non-blanching rash','dermatology,high_safety')
chip(WF,'plan_phrases','supportive care discussed','supportive care, symptomatic treatment','plan')
chip(WF,'plan_phrases','hydration discussed','hydration advice, fluid intake','plan')
chip(WF,'plan_phrases','rest advised','rest advised, take it easy','plan')
chip(WF,'plan_phrases','antipyretic use as per clinician plan','antipyretic, fever management','plan')
chip(WF,'plan_phrases','return precautions discussed','return precautions, warning signs','plan')
chip(WF,'plan_phrases','sick leave advised','sick leave, time off work','plan')
chip(WF,'follow_up','3 days if not improving','3 days, 72 hours','followup')
chip(WF,'follow_up','sooner if worsening','sooner, PRN','followup')

# ====================================================================
# 2. gp-cough: Cough / Acute bronchitis
# ====================================================================
WF = 'gp-cough'
chip(WF,'symptoms','cough','cough','acute')
chip(WF,'symptoms','dry cough','dry cough, non-productive cough','acute')
chip(WF,'symptoms','productive cough','productive cough, phlegm, sputum production','acute')
chip(WF,'symptoms','sputum color noted','sputum color, green sputum, yellow phlegm','acute')
chip(WF,'symptoms','cough duration noted','cough duration, how long cough','acute')
chip(WF,'symptoms','fever','fever, pyrexia','acute')
chip(WF,'symptoms','shortness of breath','SOB, dyspnea, breathlessness','respiratory')
chip(WF,'symptoms','wheeze','wheeze, whistling chest','respiratory')
chip(WF,'symptoms','chest pain','chest pain, pleuritic pain','respiratory')
chip(WF,'symptoms','postnasal drip','postnasal drip, drip sensation','ent')
chip(WF,'relevant_negatives','no hemoptysis','no blood in sputum, no coughing blood','respiratory')
chip(WF,'relevant_negatives','no fever','no fever, afebrile','acute')
chip(WF,'relevant_negatives','no shortness of breath','no SOB, no dyspnea','respiratory')
chip(WF,'relevant_negatives','no chest pain','no CP, no pleuritic pain','cardiac')
chip(WF,'relevant_negatives','no night sweats','no night sweats, no drenching sweats','general')
chip(WF,'relevant_negatives','no weight loss','no weight loss, no unintentional weight loss','general')
chip(WF,'relevant_negatives','no hoarseness','no hoarseness, no voice change','ent')
chip(WF,'exam_findings','chest clear on auscultation','chest clear, clear lung fields','respiratory')
chip(WF,'exam_findings','wheezes','wheezes, expiratory wheeze, polyphonic','respiratory')
chip(WF,'exam_findings','rhonchi','rhonchi, coarse breath sounds','respiratory')
chip(WF,'exam_findings','crackles','crackles, crepitations','respiratory')
chip(WF,'exam_findings','prolonged expiration','prolonged expiration, prolonged exp phase','respiratory')
chip(WF,'exam_findings','no respiratory distress','no RD, no tachypnea','respiratory')
chip(WF,'exam_findings','afebrile','afebrile','vitals')
chip(WF,'exam_findings','febrile','febrile','vitals')
chip(WF,'exam_findings','oropharynx clear','oropharynx normal','ent')
chip(WF,'red_flags','hemoptysis','hemoptysis, coughing blood','respiratory,high_safety')
chip(WF,'red_flags','significant dyspnea','moderate to severe dyspnea','respiratory,high_safety')
chip(WF,'red_flags','persistent fever >3 days','persistent fever','acute,high_safety')
chip(WF,'red_flags','immunocompromised state','immunocompromised','chronic,high_safety')
chip(WF,'red_flags','significant weight loss','weight loss unexplained','general,high_safety')
chip(WF,'red_flags','recurrent pneumonia','recurrent chest infections','respiratory,high_safety')
chip(WF,'plan_phrases','supportive care discussed','supportive care, symptomatic management','plan')
chip(WF,'plan_phrases','cough suppressant per clinician plan','cough suppressant','plan')
chip(WF,'plan_phrases','hydration advice given','stay hydrated, fluids','plan')
chip(WF,'plan_phrases','return precautions discussed','return precautions, warning signs','plan')
chip(WF,'plan_phrases','smoking cessation advised','stop smoking, quit smoking','plan')
chip(WF,'plan_phrases','follow-up arranged','follow-up, FU','plan')
chip(WF,'follow_up','1-2 weeks if not improving','1-2 weeks','followup')
chip(WF,'follow_up','sooner if worsening','sooner','followup')

# ====================================================================
# 3. gp-sore-throat: Sore throat / Pharyngitis
# ====================================================================
WF = 'gp-sore-throat'
chip(WF,'symptoms','sore throat','sore throat, throat pain','acute')
chip(WF,'symptoms','painful swallowing','painful swallowing, odynophagia','acute')
chip(WF,'symptoms','fever','fever, pyrexia','acute')
chip(WF,'symptoms','cough','cough','acute')
chip(WF,'symptoms','runny nose','runny nose, rhinorrhea','acute')
chip(WF,'symptoms','headache','headache','acute')
chip(WF,'symptoms','body aches','myalgia, body aches','acute')
chip(WF,'symptoms','swollen glands','swollen glands, neck lumps','ent')
chip(WF,'symptoms','voice change','voice change, hoarseness, muffled voice','ent')
chip(WF,'relevant_negatives','no drooling','no drooling','ent')
chip(WF,'relevant_negatives','no breathing difficulty','no stridor, no respiratory distress','respiratory')
chip(WF,'relevant_negatives','no neck swelling','no neck mass, no neck swelling','ent')
chip(WF,'relevant_negatives','no rash','no skin rash','dermatology')
chip(WF,'relevant_negatives','no cough','no cough','respiratory')
chip(WF,'relevant_negatives','no ear pain','no ear pain, no otalgia','ent')
chip(WF,'exam_findings','oropharynx erythematous','red throat, pharyngeal erythema','ent')
chip(WF,'exam_findings','tonsillar exudate','exudate, white patches on tonsils','ent')
chip(WF,'exam_findings','tonsils enlarged','swollen tonsils, tonsillar hypertrophy','ent')
chip(WF,'exam_findings','oropharynx clear','normal throat, clear pharynx','ent')
chip(WF,'exam_findings','tender cervical lymph nodes','tender LNs, neck nodes','ent')
chip(WF,'exam_findings','afebrile','afebrile','vitals')
chip(WF,'exam_findings','febrile','febrile','vitals')
chip(WF,'exam_findings','no respiratory distress','no RD','respiratory')
chip(WF,'red_flags','drooling','drooling, unable to swallow saliva','ent,high_safety')
chip(WF,'red_flags','stridor','stridor, noisy breathing','respiratory,high_safety')
chip(WF,'red_flags','trismus','trismus, difficulty opening mouth','ent,high_safety')
chip(WF,'red_flags','muffled voice','hot potato voice, muffled','ent,high_safety')
chip(WF,'red_flags','airway compromise signs','airway concern','respiratory,high_safety')
chip(WF,'investigations','rapid strep test done','rapid strep, rapid antigen test','investigations')
chip(WF,'investigations','throat swab sent','throat swab, culture','investigations')
chip(WF,'plan_phrases','symptomatic treatment discussed','symptomatic, supportive','plan')
chip(WF,'plan_phrases','hydration advised','hydrate, fluids','plan')
chip(WF,'plan_phrases','analgesics per clinician plan','pain relief','plan')
chip(WF,'plan_phrases','return precautions discussed','return precautions','plan')
chip(WF,'plan_phrases','sick leave advised','sick leave','plan')
chip(WF,'follow_up','1 week if not improving','1 week, 7 days','followup')
chip(WF,'follow_up','sooner if worsening','sooner','followup')

# ====================================================================
# 4. gp-headache: Headache / Migraine or Tension
# ====================================================================
WF = 'gp-headache'
chip(WF,'symptoms','headache','headache, head pain','acute')
chip(WF,'symptoms','headache location','frontal, temporal, occipital, bitemporal','acute')
chip(WF,'symptoms','throbbing pain','throbbing, pulsating','acute')
chip(WF,'symptoms','pressure type pain','pressure, tight band, squeezing','acute')
chip(WF,'symptoms','duration of headache','how long headache, hours, days','acute')
chip(WF,'symptoms','frequency of headaches','frequency, how often','chronic')
chip(WF,'symptoms','photophobia','photophobia, light sensitivity','neuro')
chip(WF,'symptoms','phonophobia','phonophobia, sound sensitivity','neuro')
chip(WF,'symptoms','nausea','nausea','gi')
chip(WF,'symptoms','vomiting','vomiting','gi')
chip(WF,'symptoms','visual aura','aura, visual changes before headache','neuro')
chip(WF,'symptoms','neck stiffness','neck stiffness, stiff neck','neuro')
chip(WF,'relevant_negatives','no aura','no aura','neuro')
chip(WF,'relevant_negatives','no weakness','no limb weakness, no hemiparesis','neuro')
chip(WF,'relevant_negatives','no seizure','no seizure activity','neuro')
chip(WF,'relevant_negatives','no speech difficulty','no aphasia, no dysarthria','neuro')
chip(WF,'relevant_negatives','no vision loss','no vision loss, no blindness','neuro')
chip(WF,'relevant_negatives','no neck stiffness','no neck stiffness','neuro')
chip(WF,'relevant_negatives','no fever','no fever','acute')
chip(WF,'exam_findings','alert and oriented','A&O, fully conscious','neuro')
chip(WF,'exam_findings','no focal neurological deficit','no focal deficit','neuro')
chip(WF,'exam_findings','fundoscopy normal','fundoscopy normal, discs clear','ophthalmology')
chip(WF,'exam_findings','neck supple','neck supple, no neck stiffness','neuro')
chip(WF,'exam_findings','blood pressure normal','BP normal','vitals')
chip(WF,'exam_findings','blood pressure elevated','BP high','vitals')
chip(WF,'red_flags','sudden severe headache','thunderclap, worst headache ever','neuro,high_safety')
chip(WF,'red_flags','neurological deficit','focal weakness, hemiparesis','neuro,high_safety')
chip(WF,'red_flags','seizure with headache','seizure','neuro,high_safety')
chip(WF,'red_flags','fever with headache','febrile, meningism','neuro,high_safety')
chip(WF,'red_flags','headache after age 50 new onset','new headache, elderly','neuro,high_safety')
chip(WF,'red_flags','headache with visual changes','visual disturbance, diplopia','ophthalmology,high_safety')
chip(WF,'red_flags','headache with vomiting','vomiting, projectile','gi,high_safety')
chip(WF,'plan_phrases','analgesic use per clinician plan','pain relief, analgesic','plan')
chip(WF,'plan_phrases','triptan use per clinician plan if migraine','triptan, migraine treatment','plan')
chip(WF,'plan_phrases','rest in dark quiet room advised','rest, dark room','plan')
chip(WF,'plan_phrases','hydration advised','hydration','plan')
chip(WF,'plan_phrases','headache diary advised','headache diary, trigger tracking','plan')
chip(WF,'plan_phrases','return precautions discussed','return precautions','plan')
chip(WF,'follow_up','2 weeks if persistent','2 weeks','followup')
chip(WF,'follow_up','sooner if worsening','sooner','followup')

# ====================================================================
# 5. gp-dizziness: Dizziness / Vestibular
# ====================================================================
WF = 'gp-dizziness'
chip(WF,'symptoms','dizziness','dizziness, lightheadedness','acute')
chip(WF,'symptoms','vertigo','vertigo, spinning sensation','acute')
chip(WF,'symptoms','feeling faint','presyncope, near fainting','acute')
chip(WF,'symptoms','positional symptoms','positional, triggered by head movement','vestibular')
chip(WF,'symptoms','unsteady gait','unsteady, off balance','vestibular')
chip(WF,'symptoms','onset and duration','when started, how long','acute')
chip(WF,'symptoms','nausea with dizziness','nausea','gi')
chip(WF,'symptoms','vomiting with dizziness','vomiting','gi')
chip(WF,'symptoms','tinnitus','tinnitus, ringing ears','ent')
chip(WF,'symptoms','hearing change','hearing loss, muffled hearing','ent')
chip(WF,'relevant_negatives','no syncope','no syncope, no fainting','cardiac')
chip(WF,'relevant_negatives','no focal neurological symptoms','no focal neuro, no weakness','neuro')
chip(WF,'relevant_negatives','no chest pain','no CP','cardiac')
chip(WF,'relevant_negatives','no palpitations','no palpitations','cardiac')
chip(WF,'relevant_negatives','no headache','no headache','neuro')
chip(WF,'relevant_negatives','no vision change','no vision change','ophthalmology')
chip(WF,'exam_findings','orthostatic vitals','orthostatics, BP lying standing','vitals')
chip(WF,'exam_findings','nystagmus','nystagmus','neuro')
chip(WF,'exam_findings','no nystagmus','no nystagmus','neuro')
chip(WF,'exam_findings','Dix-Hallpike test positive','Dix-Hallpike, positional test','vestibular')
chip(WF,'exam_findings','Dix-Hallpike test negative','Dix-Hallpike negative','vestibular')
chip(WF,'exam_findings','neurological examination normal','neuro exam normal','neuro')
chip(WF,'exam_findings','gait normal','gait normal','neuro')
chip(WF,'red_flags','syncope','fainting, LOC','cardiac,high_safety')
chip(WF,'red_flags','focal neurological deficit','stroke symptoms, weakness','neuro,high_safety')
chip(WF,'red_flags','chest pain','CP, cardiac','cardiac,high_safety')
chip(WF,'red_flags','palpitations','racing heart','cardiac,high_safety')
chip(WF,'red_flags','severe headache with dizziness','headache','neuro,high_safety')
chip(WF,'red_flags','hearing loss sudden','sudden deafness','ent,high_safety')
chip(WF,'plan_phrases','Epley maneuver performed','Epley, canalith repositioning','plan,vestibular')
chip(WF,'plan_phrases','vestibular rehabilitation advised','vestibular rehab, balance exercises','plan')
chip(WF,'plan_phrases','symptomatic treatment per clinician','symptomatic, vestibular suppressant','plan')
chip(WF,'plan_phrases','fall precautions discussed','fall prevention, safety','plan')
chip(WF,'plan_phrases','return precautions discussed','return precautions','plan')
chip(WF,'follow_up','1-2 weeks','1-2 weeks','followup')
chip(WF,'follow_up','sooner if worsening','sooner','followup')

# ====================================================================
# 6. gp-fatigue: Fatigue / Anaemia workup
# ====================================================================
WF = 'gp-fatigue'
chip(WF,'symptoms','fatigue','fatigue, tiredness','chronic')
chip(WF,'symptoms','duration of fatigue','fatigue duration, how long','chronic')
chip(WF,'symptoms','low energy','low energy, sluggish','chronic')
chip(WF,'symptoms','sleep quality','sleep quality, poor sleep','chronic')
chip(WF,'symptoms','appetite changes','appetite, eating changes','gi')
chip(WF,'symptoms','weight change','weight loss, weight gain','general')
chip(WF,'symptoms','mood changes','low mood, depression, anxiety','psych')
chip(WF,'symptoms','exertional symptoms','shortness of breath on exertion, legs heavy','cardiac')
chip(WF,'symptoms','pallor','pale, looking pale','general')
chip(WF,'symptoms','dizziness','dizziness','cardiac')
chip(WF,'relevant_negatives','no weight loss','no weight loss','general')
chip(WF,'relevant_negatives','no fever','no fever','acute')
chip(WF,'relevant_negatives','no night sweats','no night sweats','general')
chip(WF,'relevant_negatives','no shortness of breath','no SOB','cardiac')
chip(WF,'relevant_negatives','no chest pain','no CP','cardiac')
chip(WF,'relevant_negatives','no palpitations','no palpitations','cardiac')
chip(WF,'relevant_negatives','no bleeding','no GI bleed, no heavy periods','gi')
chip(WF,'relevant_negatives','no suicidal thoughts','no SI','psych,high_safety')
chip(WF,'exam_findings','pallor','pale, conjunctival pallor','general')
chip(WF,'exam_findings','conjunctiva pink','pink conjunctiva, normal','general')
chip(WF,'exam_findings','tachycardia','tachycardia, HR elevated','vitals')
chip(WF,'exam_findings','heart rate normal','HR normal','vitals')
chip(WF,'exam_findings','blood pressure normal','BP normal','vitals')
chip(WF,'exam_findings','general appearance well','well looking, no distress','general')
chip(WF,'red_flags','significant weight loss','unexplained weight loss','general,high_safety')
chip(WF,'red_flags','chest pain','CP','cardiac,high_safety')
chip(WF,'red_flags','shortness of breath','SOB, dyspnea','cardiac,high_safety')
chip(WF,'red_flags','bleeding signs','GI bleeding, melena','gi,high_safety')
chip(WF,'red_flags','suicidal ideation','SI, suicidal thoughts','psych,high_safety')
chip(WF,'red_flags','neurological symptoms','neuro symptoms','neuro,high_safety')
chip(WF,'investigations','CBC ordered','CBC, complete blood count','investigations')
chip(WF,'investigations','iron studies ordered','ferritin, iron, TIBC','investigations')
chip(WF,'investigations','TSH ordered','TSH, thyroid function','investigations')
chip(WF,'investigations','vitamin B12 levels ordered','B12, B12 level','investigations')
chip(WF,'investigations','vitamin D levels ordered','vitamin D, 25-OH','investigations')
chip(WF,'investigations','glucose ordered','glucose, blood sugar','investigations')
chip(WF,'plan_phrases','sleep hygiene discussed','sleep hygiene, bedtime routine','plan')
chip(WF,'plan_phrases','dietary advice given','nutrition, balanced diet','plan')
chip(WF,'plan_phrases','exercise advised','physical activity, exercise','plan')
chip(WF,'plan_phrases','investigations ordered','blood tests arranged','plan')
chip(WF,'plan_phrases','follow-up for results','results review','plan')
chip(WF,'follow_up','2-4 weeks for results','2-4 weeks','followup')
chip(WF,'follow_up','sooner if symptoms worsen','sooner','followup')

# ====================================================================
# 7. gp-abdominal-pain: Abdominal pain / Gastritis
# ====================================================================
WF = 'gp-abdominal-pain'
chip(WF,'symptoms','abdominal pain location','epigastric, upper, lower, central, diffuse','gi')
chip(WF,'symptoms','abdominal pain duration','how long, acute, chronic','gi')
chip(WF,'symptoms','burning epigastric pain','burning, gnawing, epigastric','gi')
chip(WF,'symptoms','cramping pain','crampy, colicky','gi')
chip(WF,'symptoms','bloating','bloating, distended','gi')
chip(WF,'symptoms','nausea','nausea','gi')
chip(WF,'symptoms','vomiting','vomiting','gi')
chip(WF,'symptoms','heartburn','heartburn, reflux','gi')
chip(WF,'symptoms','indigestion','indigestion, dyspepsia','gi')
chip(WF,'symptoms','belching','belching, burping','gi')
chip(WF,'symptoms','loss of appetite','poor appetite, anorexia','gi')
chip(WF,'relevant_negatives','no vomiting','no vomiting','gi')
chip(WF,'relevant_negatives','no GI bleeding','no melena, no hematemesis','gi')
chip(WF,'relevant_negatives','no dysphagia','no difficulty swallowing','gi')
chip(WF,'relevant_negatives','no weight loss','no weight loss','gi')
chip(WF,'relevant_negatives','no fever','no fever','acute')
chip(WF,'relevant_negatives','no diarrhea','no diarrhea','gi')
chip(WF,'relevant_negatives','no jaundice','no jaundice, no icterus','hepatic')
chip(WF,'relevant_negatives','no urinary symptoms','no dysuria, no frequency','renal')
chip(WF,'exam_findings','abdomen soft','soft abdomen, non-tender','gi')
chip(WF,'exam_findings','epigastric tenderness','epigastric tenderness','gi')
chip(WF,'exam_findings','generalised abdominal tenderness','general tenderness','gi')
chip(WF,'exam_findings','guarding','guarding, involuntary','gi,high_safety')
chip(WF,'exam_findings','rebound tenderness','rebound','gi,high_safety')
chip(WF,'exam_findings','bowel sounds normal','bowel sounds present, normal','gi')
chip(WF,'exam_findings','bowel sounds hyperactive','hyperactive bowels','gi')
chip(WF,'red_flags','severe persistent pain','severe pain, unable to lie still','gi,high_safety')
chip(WF,'red_flags','haematemesis','vomiting blood','gi,high_safety')
chip(WF,'red_flags','melena','black tarry stool','gi,high_safety')
chip(WF,'red_flags','peritoneal signs','guarding, rigidity, rebound','gi,high_safety')
chip(WF,'red_flags','unexplained weight loss','weight loss','gi,high_safety')
chip(WF,'red_flags','dysphagia progressive','difficulty swallowing progressive','gi,high_safety')
chip(WF,'red_flags','fever with abdominal pain','febrile, infection','gi,high_safety')
chip(WF,'investigations','abdominal ultrasound ordered','US abdomen','investigations')
chip(WF,'investigations','CBC ordered','CBC, FBC','investigations')
chip(WF,'investigations','liver function tests ordered','LFTs','investigations')
chip(WF,'investigations','amylase ordered','amylase, lipase','investigations')
chip(WF,'plan_phrases','lifestyle advice discussed','diet, avoid triggers, small meals','plan')
chip(WF,'plan_phrases','antacid use as per clinician plan','antacid, symptomatic','plan')
chip(WF,'plan_phrases','PPI use as per clinician plan','PPI, proton pump inhibitor','plan')
chip(WF,'plan_phrases','dietary modifications discussed','avoid spicy, avoid fatty','plan')
chip(WF,'plan_phrases','return precautions discussed','return precautions, warning signs','plan')
chip(WF,'follow_up','2 weeks if not improving','2 weeks','followup')
chip(WF,'follow_up','sooner if worsening','sooner','followup')

# ====================================================================
# 8. gp-nausea: Nausea / vomiting / Acute gastroenteritis
# ====================================================================
WF = 'gp-nausea'
chip(WF,'symptoms','nausea','nausea, feeling sick','gi')
chip(WF,'symptoms','vomiting','vomiting, emesis','gi')
chip(WF,'symptoms','vomiting frequency','how many times, frequency','gi')
chip(WF,'symptoms','diarrhea','diarrhea, loose stools','gi')
chip(WF,'symptoms','abdominal pain','abdominal pain, cramps','gi')
chip(WF,'symptoms','fever','fever, pyrexia','acute')
chip(WF,'symptoms','decreased oral intake','not eating, not drinking','gi')
chip(WF,'symptoms','dizziness','dizziness','gi')
chip(WF,'relevant_negatives','no blood in vomit','no hematemesis','gi')
chip(WF,'relevant_negatives','no severe dehydration','no dehydration signs','gi')
chip(WF,'relevant_negatives','no blood in stool','no melena, no hematochezia','gi')
chip(WF,'relevant_negatives','no abdominal pain severe','no severe pain','gi')
chip(WF,'relevant_negatives','no headache','no headache','neuro')
chip(WF,'relevant_negatives','no fever','no fever','acute')
chip(WF,'exam_findings','abdomen soft non-tender','abdomen benign','gi')
chip(WF,'exam_findings','epigastric tenderness','epigastric tenderness','gi')
chip(WF,'exam_findings','hydration adequate','good hydration, normal turgor','general')
chip(WF,'exam_findings','decreased skin turgor','dry, dehydration signs','general')
chip(WF,'exam_findings','mucus membranes dry','dry mouth, dry mm','general')
chip(WF,'exam_findings','afebrile','afebrile','vitals')
chip(WF,'exam_findings','tachycardia','tachycardia, HR high','vitals')
chip(WF,'red_flags','persistent vomiting','unable to keep fluids','gi,high_safety')
chip(WF,'red_flags','blood in vomit','hematemesis','gi,high_safety')
chip(WF,'red_flags','severe dehydration','severe dry, anuria','gi,high_safety')
chip(WF,'red_flags','altered mental state','confusion, drowsy','neuro,high_safety')
chip(WF,'red_flags','bilious vomiting','bile stained','gi,high_safety')
chip(WF,'red_flags','severe abdominal pain','severe pain','gi,high_safety')
chip(WF,'plan_phrases','oral rehydration advised','ORS, rehydration','plan')
chip(WF,'plan_phrases','small frequent feeds advised','bland diet, BRAT diet','plan')
chip(WF,'plan_phrases','anti-emetic use per clinician plan','anti-nausea, antiemetic','plan')
chip(WF,'plan_phrases','return precautions discussed','return precautions','plan')
chip(WF,'follow_up','2-3 days if not improving','2-3 days','followup')
chip(WF,'follow_up','sooner if worsening','sooner','followup')

# ====================================================================
# 9. gp-diarrhea: Diarrhea / Acute gastroenteritis
# ====================================================================
WF = 'gp-diarrhea'
chip(WF,'symptoms','diarrhea frequency','diarrhea how many times per day','gi')
chip(WF,'symptoms','watery stool','watery, loose, liquid','gi')
chip(WF,'symptoms','blood or mucus in stool','blood, mucus, slime','gi')
chip(WF,'symptoms','abdominal cramps','cramps, colicky pain','gi')
chip(WF,'symptoms','nausea','nausea','gi')
chip(WF,'symptoms','vomiting','vomiting','gi')
chip(WF,'symptoms','fever','fever','acute')
chip(WF,'symptoms','recent travel','travel history, foreign travel','gi')
chip(WF,'symptoms','food exposure','food poisoning, suspect food','gi')
chip(WF,'symptoms','duration of diarrhea','how long, days','gi')
chip(WF,'relevant_negatives','no blood in stool','no hematochezia','gi')
chip(WF,'relevant_negatives','no vomiting','no vomiting','gi')
chip(WF,'relevant_negatives','no fever','no fever','acute')
chip(WF,'relevant_negatives','no severe abdominal pain','no severe pain','gi')
chip(WF,'relevant_negatives','no dehydration signs','no dehydration','gi')
chip(WF,'exam_findings','abdomen soft non-tender','abdomen soft','gi')
chip(WF,'exam_findings','lower abdominal tenderness','lower abdomen tender','gi')
chip(WF,'exam_findings','hyperactive bowel sounds','bowel sounds increased','gi')
chip(WF,'exam_findings','hydration adequate','good hydration','general')
chip(WF,'exam_findings','decreased skin turgor','dry','general')
chip(WF,'exam_findings','afebrile','afebrile','vitals')
chip(WF,'red_flags','bloody diarrhea','dysentery, bloody stools','gi,high_safety')
chip(WF,'red_flags','severe dehydration','dehydration severe','gi,high_safety')
chip(WF,'red_flags','persistent fever','fever ongoing','acute,high_safety')
chip(WF,'red_flags','severe abdominal pain','severe cramps','gi,high_safety')
chip(WF,'red_flags','immunocompromised state','immunocompromised','chronic,high_safety')
chip(WF,'red_flags','elderly patient','elderly, age >65','general,high_safety')
chip(WF,'plan_phrases','oral rehydration solution advised','ORS, rehydration salts','plan')
chip(WF,'plan_phrases','bland diet advised','BRAT diet, avoid dairy','plan')
chip(WF,'plan_phrases