#!/usr/bin/env python3
"""V4 data for Gastroenterology (V5A-4D), Endocrinology (V5A-4E), Uro/Neph (V5A-4F)."""
import json, os

DATA = 'data'
HIST = f'{DATA}/v4_workflow_history_drafts.json'
EXAM = f'{DATA}/v4_workflow_exam_details.json'
INV = f'{DATA}/v4_investigation_options.json'
PLAN = f'{DATA}/v4_plan_options.json'

def load(f): return json.load(open(f))
def save(f,d): json.dump(d,open(f,'w'),indent=2)

def hist(wf,display,draft,phs):
    return {'workflow_id':wf,'workflow_display_name':display,
            'default_history_draft':f"Patient presents with {draft[0].lower()}{draft[1:]}",
            'editable_placeholders':phs,'linked_autofill_groups':['symptoms','relevant_negatives','red_flags','follow_up'],
            'optional_full_history_sections':['presenting_complaint','socrates_hpc','systems_review','pmh','drug_history','allergies','ice'],
            'safety_note':'Editable documentation draft only. Keep only details assessed or discussed by the clinician.','review_required':True}

def exam(wf,display,groups):
    eg=[]
    for gid,glab,go,ps in groups:
        eg.append({'group_id':gid,'group_label':glab,'display_order':go,
            'safety_note':f'Document only if assessed. {glab.lower()} findings only if assessed.',
            'prompts':[{'prompt_id':p[0],'prompt_text':p[1],'documentation_style':p[2],'required_level':p[3]} for p in ps]})
    return {'workflow_id':wf,'workflow_display_name':display,'exam_groups':eg,'safety_note':'Document only if assessed.','review_required':True}

def inv(wf,display,groups):
    ig=[]
    for gid,glab,opts in groups:
        ig.append({'group_id':gid,'group_label':glab,
            'options':[{'option_id':o[0],'option_text':o[1],'required_level':'conditional','source_status':'draft','note_text':o[1].split(' if')[0]+'.'} for o in opts]})
    return {'workflow_id':wf,'workflow_display_name':display,'investigation_groups':ig,'safety_note':'Documentation prompts only.','review_required':True}

def plan(wf,display,groups):
    pg=[]
    for gid,glab,opts in groups:
        pg.append({'group_id':gid,'group_label':glab,'options':[{'option_id':f'{wf}_{o[0]}','option_text':o[1],
            'option_category':o[2],'source_status':'draft','source_reference':'V5A-4 batch',
            'clinician_confirmation_required':True,'safety_note':'Documentation option only. Use only if confirmed by the clinician.',
            'note_text':o[1].split('.')[0]+'.'} for o in opts]})
    return {'workflow_id':wf,'workflow_display_name':display,'plan_option_groups':pg,
            'safety_note':'Documentation prompts only. No treatment recommendations.','review_required':True,'source_status':'draft'}

# ── GASTROENTEROLOGY ──
gastro_wfs = [
    ('gastro-gerd','Gastro GERD'),('gastro-abdominal-pain','Gastro Abdominal Pain'),
    ('gastro-ibs-symptoms','Gastro IBS Symptoms'),('gastro-constipation','Gastro Constipation'),
    ('gastro-diarrhea','Gastro Diarrhea'),('gastro-rectal-bleeding','Gastro Rectal Bleeding'),
    ('gastro-liver-enzyme-review','Gastro Liver Enzyme Review'),('gastro-jaundice-documentation','Gastro Jaundice'),
    ('gastro-dysphagia','Gastro Dysphagia'),('gastro-post-endoscopy-followup','Gastro Post Endoscopy Follow-up'),
]
g_hist = {
    'gastro-gerd': ('reflux. [Heartburn]. [Regurgitation]. [Epigastric discomfort]. [Post-prandial]. [Nocturnal]. [Trigger foods]. [Medication use].',
        ['[Heartburn]','[Regurgitation]','[Epigastric discomfort]','[Post-prandial]','[Nocturnal]','[Trigger foods]','[Medication use]']),
    'gastro-abdominal-pain': ('abdominal pain [duration]. Location [location], character [character]. [Radiation]. [Relation to meals/bowels]. [Nausea/vomiting]. [Bowel habit]. [Urinary symptoms].',
        ['[duration]','[location]','[character]','[Radiation]','[Relation to meals/bowels]','[Nausea/vomiting]','[Bowel habit]','[Urinary symptoms]']),
    'gastro-ibs-symptoms': ('IBS symptoms. [Abdominal pain/discomfort]. [Bloating]. [Bowel habit pattern]. [Diarrhoea/constipation pattern]. [Relation to stress/food].',
        ['[Abdominal pain/discomfort]','[Bloating]','[Bowel habit pattern]','[Diarrhoea/constipation pattern]','[Relation to stress/food]']),
    'gastro-constipation': ('constipation [duration]. Stool frequency [frequency], consistency [consistency]. [Straining]. [Incomplete emptying]. [Diet/fluid]. [Medication history].',
        ['[duration]','[frequency]','[consistency]','[Straining]','[Incomplete emptying]','[Diet/fluid]','[Medication history]']),
    'gastro-diarrhea': ('diarrhoea [duration]. Stool frequency [frequency], consistency [consistency]. [Blood/mucus]. [Fever]. [Vomiting]. [Travel/food exposure]. [Hydration context].',
        ['[duration]','[frequency]','[consistency]','[Blood/mucus]','[Fever]','[Vomiting]','[Travel/food exposure]','[Hydration context]']),
    'gastro-rectal-bleeding': ('rectal bleeding. Colour [colour], amount [amount]. [Relation to stool]. [Pain on defecation]. [Change in bowel habit]. [Weight loss]. [Anticoagulant use].',
        ['[colour]','[amount]','[Relation to stool]','[Pain on defecation]','[Change in bowel habit]','[Weight loss]','[Anticoagulant use]']),
    'gastro-liver-enzyme-review': ('liver enzyme review. Results: [type], trend [trend]. [Alcohol history]. [Medication/supplement history]. [Viral hepatitis risk].',
        ['[type]','[trend]','[Alcohol history]','[Medication/supplement history]','[Viral hepatitis risk]']),
    'gastro-jaundice-documentation': ('jaundice [duration]. [Dark urine]. [Pale stool]. [Pruritus]. [Abdominal pain]. [Fever]. [Weight loss]. [Medication/alcohol history].',
        ['[duration]','[Dark urine]','[Pale stool]','[Pruritus]','[Abdominal pain]','[Fever]','[Weight loss]','[Medication/alcohol history]']),
    'gastro-dysphagia': ('dysphagia [duration]. Solids vs liquids: [solids/liquids]. [Progression]. [Odynophagia]. [Reflux symptoms]. [Weight loss]. [Regurgitation].',
        ['[duration]','[solids/liquids]','[Progression]','[Odynophagia]','[Reflux symptoms]','[Weight loss]','[Regurgitation]']),
    'gastro-post-endoscopy-followup': ('post-endoscopy follow-up. Procedure [type], indication [indication]. [Findings reviewed]. [Symptoms after procedure]. [Medication/advice].',
        ['[type]','[indication]','[Findings reviewed]','[Symptoms after procedure]','[Medication/advice]']),
}
g_exam = {
    'gastro-gerd':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('epigastric','Epigastric tenderness documented if assessed.','documented_if_assessed','workflow_specific')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific')])],
    'gastro-abdominal-pain':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('tenderness','Abdominal tenderness documented if assessed.','documented_if_assessed','workflow_specific'),('guarding','Guarding/rebound documented if assessed.','documented_if_assessed','workflow_specific'),('bs','Bowel sounds documented if assessed.','documented_if_assessed','workflow_specific')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('temp','Temperature documented if measured.','if_measured','conditional')])],
    'gastro-ibs-symptoms':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('tenderness','Abdominal tenderness documented if assessed.','documented_if_assessed','workflow_specific')])],
    'gastro-constipation':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('distension','Abdominal distension documented if assessed.','documented_if_assessed','conditional')]),('rectal','Rectal examination',2,[('dre','Rectal examination documented if clinically appropriate and assessed.','documented_if_assessed','conditional')])],
    'gastro-diarrhea':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('tenderness','Abdominal tenderness documented if assessed.','documented_if_assessed','conditional')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','conditional'),('temp','Temperature documented if measured.','if_measured','conditional')]),('hydration','Hydration',3,[('hydration','Hydration documented if assessed.','documented_if_assessed','conditional')])],
    'gastro-rectal-bleeding':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific')]),('rectal','Rectal examination',2,[('dre','Rectal examination documented if clinically appropriate and assessed.','documented_if_assessed','workflow_specific')]),('vitals','Vital signs',3,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('hr','Heart rate documented if measured.','if_measured','workflow_specific')])],
    'gastro-liver-enzyme-review':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('hepatomegaly','Hepatomegaly documented if assessed.','documented_if_assessed','conditional')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','conditional')])],
    'gastro-jaundice-documentation':[('general','General examination',1,[('sclera','Scleral icterus documented if assessed.','documented_if_assessed','workflow_specific')]),('abd','Abdominal examination',2,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('hepatomegaly','Hepatomegaly documented if assessed.','documented_if_assessed','conditional')]),('vitals','Vital signs',3,[('bp','Blood pressure documented if measured.','if_measured','conditional'),('temp','Temperature documented if measured.','if_measured','conditional')])],
    'gastro-dysphagia':[('general','General examination',1,[('general','General examination documented if assessed.','documented_if_assessed','workflow_specific'),('oral','Oral/throat examination documented if assessed.','documented_if_assessed','conditional')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','conditional')])],
    'gastro-post-endoscopy-followup':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('hr','Heart rate documented if measured.','if_measured','conditional')]),('abd','Abdominal examination',2,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('tenderness','Abdominal tenderness documented if assessed.','documented_if_assessed','conditional')])],
}
g_inv = {
    'gastro-gerd':[('endoscopy','Endoscopy',[('previous_ogd','Previous endoscopy report reviewed if available.'),('hpylori','H. pylori result reviewed if available.')]),('lab','Laboratory',[('bloods','Blood tests reviewed if ordered.')])],
    'gastro-abdominal-pain':[('lab','Laboratory',[('cbc','CBC reviewed if ordered.'),('crp','CRP reviewed if ordered.'),('lft','Liver function reviewed if ordered.')]),('imaging','Imaging',[('abdominal_imaging','Abdominal imaging reviewed if available.')]),('urine','Urine',[('urinalysis','Urinalysis reviewed if performed.')])],
    'gastro-ibs-symptoms':[('lab','Laboratory',[('cbc','CBC reviewed if ordered.'),('crp','CRP reviewed if ordered.'),('coeliac','Coeliac serology reviewed if ordered.')]),('stool','Stool',[('stool_studies','Stool studies reviewed if ordered.')])],
    'gastro-constipation':[('lab','Laboratory',[('tft','Thyroid function reviewed if ordered.'),('calcium','Calcium reviewed if ordered.')])],
    'gastro-diarrhea':[('stool','Stool',[('stool_culture','Stool culture reviewed if ordered.'),('calprotectin','Calprotectin reviewed if ordered.')]),('lab','Laboratory',[('cbc','CBC reviewed if ordered.'),('crp','CRP reviewed if ordered.')])],
    'gastro-rectal-bleeding':[('lab','Laboratory',[('cbc','CBC reviewed if ordered.'),('coagulation','Coagulation reviewed if ordered.')]),('endoscopy','Endoscopy',[('previous_colonoscopy','Previous colonoscopy/endoscopy report reviewed if available.')])],
    'gastro-liver-enzyme-review':[('lab','Laboratory',[('lft','Liver function tests reviewed.'),('viral_hepatitis','Viral hepatitis serology reviewed if ordered.')]),('imaging','Imaging',[('ultrasound','Abdominal ultrasound report reviewed if available.')])],
    'gastro-jaundice-documentation':[('lab','Laboratory',[('lft','Liver function tests reviewed if ordered.'),('bilirubin','Bilirubin reviewed if ordered.')]),('imaging','Imaging',[('ultrasound','Abdominal ultrasound/imaging reviewed if available.')])],
    'gastro-dysphagia':[('endoscopy','Endoscopy',[('previous_ogd','Previous endoscopy report reviewed if available.')]),('imaging','Imaging',[('barium_swallow','Barium swallow report reviewed if performed.')])],
    'gastro-post-endoscopy-followup':[('endoscopy','Endoscopy',[('endoscopy_report','Endoscopy report reviewed.'),('histology','Histology/pathology reviewed if available.')])],
}
g_plan = {
    'gastro-gerd':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('lifestyle','Lifestyle advice documented if discussed.','patient_instruction_documentation')]),('medication','Medication plan',[('ppi','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up'),('safety_netting','Safety-netting documented if discussed.','safety_netting')])],
    'gastro-abdominal-pain':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'gastro-ibs-symptoms':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('dietary','Lifestyle/dietary advice documented if discussed.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'gastro-constipation':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('dietary','Dietary/lifestyle advice documented if discussed.','patient_instruction_documentation')]),('medication','Medication plan',[('laxative','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up')])],
    'gastro-diarrhea':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'gastro-rectal-bleeding':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'gastro-liver-enzyme-review':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up testing documented if arranged by clinician.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'gastro-jaundice-documentation':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'gastro-dysphagia':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (OGD) documented if clinician decided.','follow_up')])],
    'gastro-post-endoscopy-followup':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up plan documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up'),('safety_netting','Safety-netting documented if discussed.','safety_netting')])],
}

# ── ENDOCRINOLOGY ──
endo_wfs = [
    ('endo-diabetes-followup','Endo Diabetes Follow-up'),('endo-thyroid-symptoms','Endo Thyroid Symptoms'),
    ('endo-hypothyroidism-followup','Endo Hypothyroidism Follow-up'),('endo-hyperthyroidism-followup','Endo Hyperthyroidism Follow-up'),
    ('endo-obesity-counseling-documentation','Endo Obesity Counseling'),('endo-hypoglycemia-review','Endo Hypoglycemia Review'),
    ('endo-pcos-metabolic-review','Endo PCOS Metabolic Review'),('endo-osteoporosis-followup','Endo Osteoporosis Follow-up'),
    ('endo-adrenal-incidentaloma-referral','Endo Adrenal Incidentaloma'),('endo-pituitary-symptoms-documentation','Endo Pituitary Symptoms'),
]
e_hist = {
    'endo-diabetes-followup':('diabetes follow-up. [Home glucose]. [HbA1c trend]. [Medication adherence]. [Lifestyle]. [Hypoglycaemia symptoms]. [Foot/visual/neuropathy symptoms].',['[Home glucose]','[HbA1c trend]','[Medication adherence]','[Lifestyle]','[Hypoglycaemia symptoms]','[Foot/visual/neuropathy symptoms]']),
    'endo-thyroid-symptoms':('thyroid symptoms. [Weight change]. [Heat/cold intolerance]. [Palpitations]. [Tremor]. [Bowel habit]. [Mood/energy]. [Neck swelling/goiter].',['[Weight change]','[Heat/cold intolerance]','[Palpitations]','[Tremor]','[Bowel habit]','[Mood/energy]','[Neck swelling/goiter]']),
    'endo-hypothyroidism-followup':('hypothyroidism follow-up. [Fatigue/energy]. [Cold intolerance]. [Weight change]. [Constipation]. [Dry skin/hair loss]. [Adherence].',['[Fatigue/energy]','[Cold intolerance]','[Weight change]','[Constipation]','[Dry skin/hair loss]','[Adherence]']),
    'endo-hyperthyroidism-followup':('hyperthyroidism follow-up. [Palpitations]. [Heat intolerance]. [Tremor]. [Weight change]. [Anxiety/irritability]. [Bowel habit]. [Eye symptoms]. [Adherence].',['[Palpitations]','[Heat intolerance]','[Tremor]','[Weight change]','[Anxiety/irritability]','[Bowel habit]','[Eye symptoms]','[Adherence]']),
    'endo-obesity-counseling-documentation':('weight management. BMI [BMI]. Weight trend [trend]. [Diet context]. [Physical activity]. [Sleep]. [Comorbidities]. [Medication history].',['[BMI]','[trend]','[Diet context]','[Physical activity]','[Sleep]','[Comorbidities]','[Medication history]']),
    'endo-hypoglycemia-review':('hypoglycaemia review. Episode frequency [frequency]. Timing [timing]. [Symptoms]. [Glucose values]. [Medication context]. [Meal/activity context]. [Awareness].',['[frequency]','[timing]','[Symptoms]','[Glucose values]','[Medication context]','[Meal/activity context]','[Awareness]']),
    'endo-pcos-metabolic-review':('PCOS metabolic review. Cycle pattern [cycles]. Weight/BMI [weight]. [Acne/hirsutism]. [Glucose/insulin resistance]. [Fertility concern]. [Lifestyle].',['[cycles]','[weight]','[Acne/hirsutism]','[Glucose/insulin resistance]','[Fertility concern]','[Lifestyle]']),
    'endo-osteoporosis-followup':('osteoporosis follow-up. [Fracture history]. [Falls history]. [Back pain/height loss]. [Calcium/vitamin D]. [Adherence]. [Side effects].',['[Fracture history]','[Falls history]','[Back pain/height loss]','[Calcium/vitamin D]','[Adherence]','[Side effects]']),
    'endo-adrenal-incidentaloma-referral':('adrenal incidentaloma. [Imaging finding]. [Symptoms]. [Blood pressure]. [Weight change]. [Bruising/striae]. [Weakness/fatigue]. [Electrolytes].',['[Imaging finding]','[Symptoms]','[Blood pressure]','[Weight change]','[Bruising/striae]','[Weakness/fatigue]','[Electrolytes]']),
    'endo-pituitary-symptoms-documentation':('pituitary symptoms. [Headache]. [Visual symptoms]. [Menstrual/sexual function]. [Growth/weight changes]. [Fatigue/weakness]. [Galactorrhoea].',['[Headache]','[Visual symptoms]','[Menstrual/sexual function]','[Growth/weight changes]','[Fatigue/weakness]','[Galactorrhoea]']),
}
e_exam = {
    'endo-diabetes-followup':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('weight','Weight/BMI documented if measured.','if_measured','workflow_specific')]),('foot','Foot examination',2,[('foot_exam','Foot examination documented if assessed.','documented_if_assessed','workflow_specific'),('pulses','Peripheral pulses documented if assessed.','documented_if_assessed','conditional'),('sensation','Sensation documented if assessed.','documented_if_assessed','conditional')]),('injection','Injection sites',3,[('injection_sites','Injection sites documented if assessed.','documented_if_assessed','conditional')])],
    'endo-thyroid-symptoms':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('pulse','Pulse documented if measured.','if_measured','workflow_specific')]),('neck','Neck examination',2,[('neck','Neck/thyroid examination documented if assessed.','documented_if_assessed','workflow_specific'),('tremor','Tremor documented if assessed.','documented_if_assessed','conditional')])],
    'endo-hypothyroidism-followup':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('pulse','Pulse documented if measured.','if_measured','workflow_specific'),('weight','Weight documented if measured.','if_measured','workflow_specific')]),('neck','Neck examination',2,[('neck','Neck/thyroid examination documented if assessed.','documented_if_assessed','workflow_specific')])],
    'endo-hyperthyroidism-followup':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('pulse','Pulse documented if measured.','if_measured','workflow_specific')]),('neck','Neck examination',2,[('neck','Thyroid examination documented if assessed.','documented_if_assessed','workflow_specific'),('eyes','Eye signs documented if assessed.','documented_if_assessed','conditional'),('tremor','Tremor documented if assessed.','documented_if_assessed','conditional')])],
    'endo-obesity-counseling-documentation':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('weight','Weight/BMI documented if measured.','if_measured','workflow_specific'),('waist','Waist circumference documented if measured.','if_measured','conditional')])],
    'endo-hypoglycemia-review':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('glucose','Glucose documented if measured.','if_measured','workflow_specific')]),('general','General',2,[('appearance','General appearance documented if assessed.','documented_if_assessed','conditional')])],
    'endo-pcos-metabolic-review':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('weight','Weight/BMI documented if measured.','if_measured','workflow_specific')]),('skin','Skin examination',2,[('acne_hirsutism','Acne/hirsutism documented if assessed.','documented_if_assessed','workflow_specific')])],
    'endo-osteoporosis-followup':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','conditional'),('weight','Weight documented if measured.','if_measured','workflow_specific')]),('musculoskeletal','Musculoskeletal',2,[('gait','Gait/falls risk documented if assessed.','documented_if_assessed','workflow_specific'),('spine','Spine tenderness documented if assessed.','documented_if_assessed','conditional')])],
    'endo-adrenal-incidentaloma-referral':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('weight','Weight documented if measured.','if_measured','conditional')]),('general','General',2,[('appearance','General appearance documented if assessed.','documented_if_assessed','workflow_specific')])],
    'endo-pituitary-symptoms-documentation':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','conditional')]),('neuro','Neurological',2,[('visual_fields','Visual fields documented if assessed.','documented_if_assessed','workflow_specific'),('neuro_screen','Neurological screen documented if assessed.','documented_if_assessed','workflow_specific')])],
}
e_inv = {
    'endo-diabetes-followup':[('lab','Laboratory',[('hba1c','HbA1c reviewed if available.'),('renal','Renal function reviewed if ordered.'),('acr','Urine ACR reviewed if ordered.'),('lipid','Lipid profile reviewed if ordered.'),('eye_screening','Eye screening report reviewed if available.')])],
    'endo-thyroid-symptoms':[('lab','Laboratory',[('tft','Thyroid function tests reviewed if ordered.'),('antibodies','Thyroid antibodies reviewed if available.')]),('imaging','Imaging',[('us_thyroid','Thyroid ultrasound report reviewed if available.')])],
    'endo-hypothyroidism-followup':[('lab','Laboratory',[('tsh','TSH reviewed if available.'),('free_t4','Free T4 reviewed if available.')])],
    'endo-hyperthyroidism-followup':[('lab','Laboratory',[('tft','Thyroid function tests reviewed if available.'),('antibodies','TSI/antibody levels reviewed if ordered.')])],
    'endo-obesity-counseling-documentation':[('lab','Laboratory',[('hba1c','HbA1c/glucose reviewed if ordered.'),('lipid','Lipid profile reviewed if ordered.'),('tft','Thyroid function reviewed if ordered.')])],
    'endo-hypoglycemia-review':[('lab','Laboratory',[('hba1c','HbA1c reviewed if available.'),('glucose_log','Glucose log reviewed if available.'),('medication_list','Medication list reviewed if available.')])],
    'endo-pcos-metabolic-review':[('lab','Laboratory',[('hba1c','HbA1c/glucose reviewed if ordered.'),('lipid','Lipid profile reviewed if ordered.'),('hormonal','Hormonal profile reviewed if available.')])],
    'endo-osteoporosis-followup':[('imaging','Imaging',[('dexa','DEXA report reviewed if available.')]),('lab','Laboratory',[('calcium','Calcium/vitamin D reviewed if ordered.'),('renal','Renal function reviewed if ordered.')])],
    'endo-adrenal-incidentaloma-referral':[('imaging','Imaging',[('ct_mri','CT/MRI report reviewed if available.')]),('lab','Laboratory',[('hormonal','Hormonal workup reviewed if ordered.'),('electrolytes','Electrolytes reviewed if ordered.')])],
    'endo-pituitary-symptoms-documentation':[('imaging','Imaging',[('mri_pituitary','Pituitary MRI reviewed if available.')]),('lab','Laboratory',[('hormonal','Hormonal profile reviewed if ordered.')])],
}
e_plan = {
    'endo-diabetes-followup':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('lifestyle','Lifestyle advice documented if discussed.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation'),('glucose_monitoring','Glucose monitoring documented if discussed.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician arranged.','follow_up')])],
    'endo-thyroid-symptoms':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'endo-hypothyroidism-followup':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation'),('adherence','Adherence discussed if applicable.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up')])],
    'endo-hyperthyroidism-followup':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'endo-obesity-counseling-documentation':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('lifestyle','Lifestyle counseling documented if discussed.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'endo-hypoglycemia-review':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('medication','Medication plan',[('medication_adjustment','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up')])],
    'endo-pcos-metabolic-review':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('lifestyle','Lifestyle advice documented if discussed.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral documented if clinician decided.','follow_up')])],
    'endo-osteoporosis-followup':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('supplement','Supplement plan documented if clinician decided.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up')])],
    'endo-adrenal-incidentaloma-referral':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (endocrinology) documented if clinician arranged.','follow_up')])],
    'endo-pituitary-symptoms-documentation':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (endocrinology) documented if clinician arranged.','follow_up')])],
}

# ── UROLOGY / NEPHROLOGY ──
uro_wfs = [
    ('uro-dysuria-uti-symptoms','Uro Dysuria/UTI'),('uro-hematuria','Uro Hematuria'),
    ('uro-luts-bph','Uro LUTS/BPH'),('uro-renal-colic-followup','Uro Renal Colic Follow-up'),
    ('uro-urinary-retention-documentation','Uro Urinary Retention'),('uro-flank-pain','Uro Flank Pain'),
    ('uro-frequency-urgency','Uro Frequency/Urgency'),('neph-ckd-followup','Neph CKD Follow-up'),
    ('neph-proteinuria','Neph Proteinuria'),('neph-electrolyte-abnormality-review','Neph Electrolyte Abnormality'),
]
u_hist = {
    'uro-dysuria-uti-symptoms':('dysuria for [duration]. [Urinary frequency]. [Urgency]. [Suprapubic discomfort]. [Fever]. [Flank pain]. [Haematuria].',['[duration]','[Urinary frequency]','[Urgency]','[Suprapubic discomfort]','[Fever]','[Flank pain]','[Haematuria]']),
    'uro-hematuria':('haematuria. Visible vs microscopic: [type]. [Dysuria]. [Flank pain]. [Frequency/urgency]. [Anticoagulant use]. [Smoking/occupational exposure].',['[type]','[Dysuria]','[Flank pain]','[Frequency/urgency]','[Anticoagulant use]','[Smoking/occupational exposure]']),
    'uro-luts-bph':('LUTS. [Weak stream]. [Hesitancy]. [Nocturia]. [Urgency/frequency]. [Incomplete emptying]. [Retention history]. [Medication history].',['[Weak stream]','[Hesitancy]','[Nocturia]','[Urgency/frequency]','[Incomplete emptying]','[Retention history]','[Medication history]']),
    'uro-renal-colic-followup':('renal colic follow-up. [Flank pain progress]. [Pain radiation]. [Haematuria]. [Nausea/vomiting]. [Fever]. [Previous stone history].',['[Flank pain progress]','[Pain radiation]','[Haematuria]','[Nausea/vomiting]','[Fever]','[Previous stone history]']),
    'uro-urinary-retention-documentation':('urinary retention. Onset [onset]. [Voiding difficulty]. [Suprapubic discomfort]. [Previous retention]. [Medication history]. [Neurological symptoms].',['[onset]','[Voiding difficulty]','[Suprapubic discomfort]','[Previous retention]','[Medication history]','[Neurological symptoms]']),
    'uro-flank-pain':('flank pain [duration]. Character [character]. [Radiation]. [Urinary symptoms]. [Fever]. [Nausea/vomiting]. [Previous stones].',['[duration]','[character]','[Radiation]','[Urinary symptoms]','[Fever]','[Nausea/vomiting]','[Previous stones]']),
    'uro-frequency-urgency':('urinary frequency/urgency. [Nocturia]. [Urge incontinence]. [Dysuria]. [Haematuria]. [Fluid/caffeine context].',['[Nocturia]','[Urge incontinence]','[Dysuria]','[Haematuria]','[Fluid/caffeine context]']),
    'neph-ckd-followup':('CKD follow-up. [Renal function trend]. [Blood pressure]. [Oedema]. [Urinary symptoms]. [Medication review]. [Nephrotoxic exposure].',['[Renal function trend]','[Blood pressure]','[Oedema]','[Urinary symptoms]','[Medication review]','[Nephrotoxic exposure]']),
    'neph-proteinuria':('proteinuria. [ACR/proteinuria result]. [Oedema]. [Blood pressure]. [Diabetes/hypertension context]. [Urinary symptoms].',['[ACR/proteinuria result]','[Oedema]','[Blood pressure]','[Diabetes/hypertension context]','[Urinary symptoms]']),
    'neph-electrolyte-abnormality-review':('electrolyte abnormality review. [Abnormal value]. [Trend]. [Symptoms]. [Medication history]. [Renal function]. [Fluid intake].',['[Abnormal value]','[Trend]','[Symptoms]','[Medication history]','[Renal function]','[Fluid intake]']),
}
u_exam = {
    'uro-dysuria-uti-symptoms':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('temp','Temperature documented if measured.','if_measured','workflow_specific')]),('abd','Abdominal examination',2,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('suprapubic','Suprapubic tenderness documented if assessed.','documented_if_assessed','workflow_specific'),('cva','Flank/CVA tenderness documented if assessed.','documented_if_assessed','workflow_specific')]),('hydration','Hydration',3,[('hydration','Hydration documented if assessed.','documented_if_assessed','conditional')])],
    'uro-hematuria':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific')]),('abd','Abdominal examination',2,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('flank','Flank tenderness documented if assessed.','documented_if_assessed','workflow_specific')])],
    'uro-luts-bph':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('bladder','Bladder distension documented if assessed.','documented_if_assessed','conditional')]),('rectal','Rectal examination',2,[('dre','Digital rectal examination documented if assessed.','documented_if_assessed','conditional')]),('vitals','Vital signs',3,[('bp','Blood pressure documented if measured.','if_measured','conditional')])],
    'uro-renal-colic-followup':[('abd','Abdominal/flank examination',1,[('abdominal','Abdominal and flank examination documented if assessed.','documented_if_assessed','workflow_specific'),('cva','CVA tenderness documented if assessed.','documented_if_assessed','workflow_specific')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','conditional'),('temp','Temperature documented if measured.','if_measured','conditional')])],
    'uro-urinary-retention-documentation':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific'),('bladder','Bladder distension documented if assessed.','documented_if_assessed','workflow_specific')]),('neuro','Neurological',2,[('neuro','Neurological screen documented if assessed.','documented_if_assessed','conditional')]),('vitals','Vital signs',3,[('bp','Blood pressure documented if measured.','if_measured','conditional')])],
    'uro-flank-pain':[('abd','Abdominal/flank examination',1,[('abdominal','Abdominal and flank tenderness documented if assessed.','documented_if_assessed','workflow_specific'),('cva','CVA tenderness documented if assessed.','documented_if_assessed','workflow_specific')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','conditional'),('temp','Temperature documented if measured.','if_measured','conditional')])],
    'uro-frequency-urgency':[('abd','Abdominal examination',1,[('abdominal','Abdominal examination documented if assessed.','documented_if_assessed','workflow_specific')]),('vitals','Vital signs',2,[('bp','Blood pressure documented if measured.','if_measured','conditional')])],
    'neph-ckd-followup':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('weight','Weight documented if measured.','if_measured','workflow_specific')]),('general','Fluid status',2,[('oedema','Oedema documented if assessed.','documented_if_assessed','workflow_specific')])],
    'neph-proteinuria':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('weight','Weight documented if measured.','if_measured','conditional')]),('general','Fluid status',2,[('oedema','Oedema documented if assessed.','documented_if_assessed','workflow_specific')])],
    'neph-electrolyte-abnormality-review':[('vitals','Vital signs',1,[('bp','Blood pressure documented if measured.','if_measured','workflow_specific'),('hr','Heart rate documented if measured.','if_measured','workflow_specific')]),('general','General',2,[('hydration','Hydration/fluid status documented if assessed.','documented_if_assessed','conditional')])],
}
u_inv = {
    'uro-dysuria-uti-symptoms':[('urine','Urinalysis',[('dipstick','Urinalysis reviewed if performed.'),('culture','Urine culture reviewed if available.')]),('lab','Laboratory',[('cbc','CBC reviewed if ordered.'),('crp','CRP reviewed if ordered.'),('renal','Renal function reviewed if ordered.')])],
    'uro-hematuria':[('urine','Urinalysis',[('urinalysis','Urinalysis reviewed if performed.'),('microscopy','Urine microscopy/culture reviewed if available.')]),('lab','Laboratory',[('renal','Renal function reviewed if ordered.')]),('imaging','Imaging',[('us_kub','Renal tract imaging reviewed if available.')])],
    'uro-luts-bph':[('urine','Urinalysis',[('urinalysis','Urinalysis reviewed if performed.')]),('lab','Laboratory',[('psa','PSA result reviewed if clinician arranged and available.'),('renal','Renal function reviewed if ordered.')])],
    'uro-renal-colic-followup':[('urine','Urinalysis',[('urinalysis','Urinalysis reviewed if performed.')]),('lab','Laboratory',[('renal','Renal function reviewed if ordered.')]),('imaging','Imaging',[('ct_kub','CT/KUB imaging reviewed if available.')])],
    'uro-urinary-retention-documentation':[('urine','Urinalysis',[('urinalysis','Urinalysis reviewed if performed.')]),('lab','Laboratory',[('renal','Renal function reviewed if ordered.')]),('bedside','Bedside',[('bladder_scan','Bladder scan result reviewed if performed.')])],
    'uro-flank-pain':[('urine','Urinalysis',[('urinalysis','Urinalysis reviewed if performed.')]),('lab','Laboratory',[('cbc','CBC reviewed if ordered.'),('crp','CRP reviewed if ordered.'),('renal','Renal function reviewed if ordered.')]),('imaging','Imaging',[('ct_kub','CT/KUB/ultrasound imaging reviewed if available.')])],
    'uro-frequency-urgency':[('urine','Urinalysis',[('urinalysis','Urinalysis reviewed if performed.'),('culture','Urine culture reviewed if available.')]),('lab','Laboratory',[('glucose','Glucose/HbA1c reviewed if ordered.')])],
    'neph-ckd-followup':[('lab','Laboratory',[('renal','Renal function reviewed.'),('egfr','eGFR reviewed.'),('acr','Urine ACR/proteinuria reviewed if available.'),('electrolytes','Electrolytes reviewed if ordered.')])],
    'neph-proteinuria':[('urine','Urinalysis',[('acr','Urine ACR/proteinuria reviewed.'),('urinalysis','Urinalysis reviewed if performed.')]),('lab','Laboratory',[('renal','Renal function reviewed if ordered.')])],
    'neph-electrolyte-abnormality-review':[('lab','Laboratory',[('electrolytes','Electrolytes reviewed.'),('renal','Renal function reviewed if ordered.'),('repeat','Repeat blood tests reviewed if available.')]),('bedside','Bedside',[('ecg','ECG reviewed if performed by clinician.')])],
}
u_plan = {
    'uro-dysuria-uti-symptoms':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('hydration','Hydration advice documented if discussed.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('safety_netting','Safety-netting documented if discussed.','safety_netting')])],
    'uro-hematuria':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (urology) documented if clinician decided.','follow_up')])],
    'uro-luts-bph':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('lifestyle','Lifestyle advice documented if discussed.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (urology) documented if clinician decided.','follow_up')])],
    'uro-renal-colic-followup':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('safety_netting','Safety-netting documented if discussed.','safety_netting')])],
    'uro-urinary-retention-documentation':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (urology) documented if clinician decided.','follow_up'),('safety_netting','Safety-netting documented if discussed.','safety_netting')])],
    'uro-flank-pain':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (urology) documented if clinician decided.','follow_up')])],
    'uro-frequency-urgency':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('lifestyle','Bladder training/fluid advice documented if discussed.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (urology/continence) documented if clinician decided.','follow_up')])],
    'neph-ckd-followup':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('lifestyle','Lifestyle/dietary advice documented if discussed.','patient_instruction_documentation')]),('medication','Medication',[('medication_review','Medication review documented if clinician performed.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (nephrology) documented if clinician decided.','follow_up')])],
    'neph-proteinuria':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation')]),('medication','Medication plan',[('medication_plan','Medication plan documented if clinician decided.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up documented if arranged.','follow_up'),('referral','Referral (nephrology) documented if clinician decided.','follow_up')])],
    'neph-electrolyte-abnormality-review':[('management','Management',[('clinician_plan','Clinician-entered plan documented.','patient_instruction_documentation'),('safety_netting','Safety-netting documented if discussed.','safety_netting')]),('medication','Medication',[('medication_review','Medication review documented if clinician performed.','patient_instruction_documentation')]),('follow_up','Follow-up',[('follow_up','Follow-up testing documented if arranged.','follow_up'),('referral','Referral (nephrology) documented if clinician decided.','follow_up')])],
}

# Build and save - run Endo + Uro/Neph (Gastro already committed in V5A-4D)
for name, wfs, h_defs, e_defs, i_defs, p_defs in [
    ('endocrinology', endo_wfs, e_hist, e_exam, e_inv, e_plan),
    ('urology_nephrology', uro_wfs, u_hist, u_exam, u_inv, u_plan),
]:
    history=load(HIST); ex=load(EXAM); inv_data=load(INV); plans=load(PLAN)
    start=len(history)
    for wf_id,display in wfs:
        dt,phs=h_defs[wf_id]; history.append(hist(wf_id,display,dt,phs))
        ex.append(exam(wf_id,display,e_defs[wf_id]))
        inv_data.append(inv(wf_id,display,i_defs[wf_id]))
        plans.append(plan(wf_id,display,p_defs[wf_id]))
    save(HIST,history); save(EXAM,ex); save(INV,inv_data); save(PLAN,plans)
    print(f'{name}: {len(history)-start} workflows added. Total: {len(history)}')
